language: python
python:
  - 3.5
  - 3.6
  - 3.7

install:
  - pip install cython
  - pip install matplotlib scipy
  #- pip install nose
  - pip install pint
  - python setup.py install

script:
  #- nosetests
  - pytest


after_success:
  - coveralls
