language: python
python:
  - 2.7

install:
  - pip install cython
  - pip install matplotlib scipy
  #- pip install nose
  - pip install pint
  - python setup.py install

script:
  #- nosetests
  - pytest


after_success:
  - coveralls
